//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recuritment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CandidateMaster
    {
        public int Id { get; set; }
        public string CandidateName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Discription { get; set; }
        public string Skills { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public Nullable<int> Created { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Modified { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
